# Generated by Django 3.0.2 on 2020-02-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.ClassRoom'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Student'),
        ),
    ]
